spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=caixaverso_desafio;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.username=caixaverso
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.show-sql=true

