services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: caixa_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Senha123!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  api:
    build: .
    container_name: caixa_api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Senha123!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  sqldata: